server:
  port: 9060
spring:
  application:
    name: delay-flight-service
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: localhost:8848
  #        group: df
  #      config:
  #        server-addr: localhost:8848
  #        group: df
  #        file-extension: yaml
  #        # nacos里配置的的命名空间
  #        namespace: prod
  datasource:
    url: jdbc:mysql://localhost:3306/reportform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root2018
    druid:
      filters: stat,wall
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      maxOpenPreparedStatements: 20
  redis:
    host: 127.0.0.1
    password: redis2022
    port: 6379
    database: 1
  servlet:
    multipart:
      max-file-size: 150MB        #上传单个文件最大大小，默认为1MB
      max-request-size: 200MB    #多文件上传总大小，默认为10MB

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    # 微服务架构中关闭一级缓存，防止别的服务更新后无法查询最新的数据
    local-cache-scope: statement
    jdbc-type-for-null: 'null'

sys:
  common:
    swagger:
      enabled: true
      description: 物流报表系统
      base-package: com.sys.manager.controller
      title: 物流报表系统
      version: 1.0.0

logging:
  level:
    org.activiti.engine.impl.persistence.entity: debug